const SAVE_LOCAL_DATA = 'SAVE_LOCAL_DATA';
const GET_LOCAL_DATA = 'GET_LOCAL_DATA';
const DELETE_LOCAL_DATA = 'DELETE_LOCAL_DATA';

export const REGISTER = {
    SAVE_LOCAL_DATA,
    GET_LOCAL_DATA,
    DELETE_LOCAL_DATA,
};
