const SAVE_TO_STORAGE = 'SAVE_TO_STORAGE';
const GET_FROM_STORAGE = 'GET_FROM_STORAGE';
const CLEAR_STORAGE = 'CLEAR_STORAGE';
const LOAD_DATA_TO_REDUCER = 'LOAD_DATA_TO_REDUCER';
const REMOVE_FROM_STORAGE = 'REMOVE_FROM_STORAGE';

export const STORAGE = {
    SAVE_TO_STORAGE,
    GET_FROM_STORAGE,
    CLEAR_STORAGE,
    LOAD_DATA_TO_REDUCER,
    REMOVE_FROM_STORAGE,
};
