const SAVE_TO_STORAGE = 'SAVE_TO_STORAGE';
const GET_FROM_STORAGE = 'GET_FROM_STORAGE';
const CLEAR_STORAGE = 'CLEAR_STORAGE';

export const STORAGE = {
    SAVE_TO_STORAGE,
    GET_FROM_STORAGE,
    CLEAR_STORAGE
};
