// signIn and signOut
const SIGNIN = 'SIGNIN';
const SIGNUP = 'SIGNUP';
const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
const SIGNOUT = 'SIGNOUT';
// load and unoad user signedIn in a local session
const LOAD_USER = 'LOAD_USER';
const UNLOAD_USER = 'UNLOAD_USER';
const CLEAN_SUCCESS_REGISTER = 'CLEAN_SUCCESS_REGISTER';
const UPDATE_USER_UPLOADED_STATUS = 'UPDATE_USER_UPLOADED_STATUS';

export const USER = {
    SIGNIN,
    SIGNOUT,
    SIGNUP,
    SUCCESS_REGISTER,
    LOAD_USER,
    UNLOAD_USER,
    CLEAN_SUCCESS_REGISTER,
    UPDATE_USER_UPLOADED_STATUS,
};
